apiVersion: v1
kind: Namespace
metadata:
  name: galvanic
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/skip-inbound-ports: "4222"
    config.linkerd.io/skip-outbound-ports: "4222"
  labels:
    role: galvanic-system
    access: galvanic-system
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: galvanic-fn
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/skip-inbound-ports: "4222"
    config.linkerd.io/skip-outbound-ports: "4222"
  labels:
    istio-injection: enabled
    role: galvanic-fn
